language: elixir
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker and GitHub credentials
    - secure: "4atftpM2Kw73Pw7RV4dgXLn/rLcGXdrG9aAi/N0V+S0TGIh7Y6odf1xdN6IvErn/8DUA1Ol03GwcSQvwhMUcw0bP9m59VPbQz7wNxR/NYx69CkaYkdIniXFRcZ4EGSNz4yAN81Xd0z37JLq5ZvhFoZHpXj+9cOwJL7Wd/emuEYYPlCGkdvZmdvD5a5xeM6Rq9UlWQSXg7yACxOOb1/0SUnGqnGoNDYtzJB3vZumeFG737fu3p1V/Cc/Ac+rfdrKa1LLNOC/uNxSNpzemdz0erP9664qB5Z+jQAfltcGNtVaUxnPpwlZRkCIHDD4iXEeGf9OyLC9L5zUmYXmoCkgVmzvWNk7UD3dMx1QViLjIanIIYB0UlMRyzfw+gKmog/gw680bN5Q0aprsBT2vKpMEyjvGHPz0LNvhulhNbYddAjrYb8xJtCWiDTc8xCQSfjUDdUdNiuNWyv4+/6DJ7jSyPoqXNs49qi7gVIogBe2mqJHwsp5U/oiAgXbrkbwupZaWaRQ76pX3pUX5q5+BieopsBwrNOIxJuuMhMoe0v5GfKupEWvgy9IaSps4aHX6N23ztxdOnP5XJyfj9MY+oAoCALNOluW1bkpqxHuD6Ibxc//WnST+aTqPQwN8fOq9DfrzwUoj5TWaLWPCtYCWFzi8X+hiKdlqULf6p9dBASTMaa4="
    - secure: "PrcBcTb5Nd6X/U6Sx8aWwMYzQ1+2FzeLox9NLGuQUzrHXQCq12DrAXTKIwZoBHxmATkvrxT+S2kbQAecCcliUUY6su7bCtV4XVYjJntRSpGy9QW5O4Gsw1bi0ECKv9ANSuJPBfAHSYpFx4h4ppbSPEMziL+xk3RIlX1zMrCzMa2IMrv6ZwET2xNoxPKcO1WVV1jLfLb/UHmC0WsJIVD5v5r19hjDNaX+fk0VM8ngPD2Lv08UrDQPD6sqUFtSvKp+ID6nZ1wywZ5Zd0t/LeidiFNjYfg74Wo/lBjLXWfxLKAlOd7PaxFdvizl3McjgYK9D2Zy1BN39x7om+ccLJUiBidi39wJKO4yZ3Mvy4li1LiaG2NjwQ3Si0bkJ5k+Y4J3KkWzGzWTLfimX82XmvC837AXV5QsrjA1ZVn5dw09pZq/FGWPvYKaGq94njmp9FSj+1ZI4ajwc6et1N2mgstVUKesgKM9eYRWfdG/D3Xu+TGZv5oYsS28VFqu6MBlAbEia4rr+eeE2hL9zyIXRTRRrIa+C7uPNkCHuEsr4vj9m7yR8OarqWxznyNEHVzXPYJTzDP+tdmMIMcXvlwXqTVE4Q+53lqwx8VG8q3iBbB292KXWp0srwciabsF9bS0//FDRm22dOMQ5ZxSMkrh63y2EBg7sbxG3Pn02U0U1cmVNWs="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Install dependencies
  - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
      echo "[E] Container is not started\!";
      docker logs ops --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - "CONTAINER_HTTP_HOST=localhost CONTAINER_HTTP_PORT=4000 mix test test/acceptance"
after_failure:
  - docker logs ops --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
